import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css';
import '@/styles/scss/style.scss';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import Script from 'next/script';

export default function App({ Component, pageProps, isHome }) {
  return (
    <>
      <Head>
        <title>Debt Solutions Group</title>
        <meta name="description" content="Generated by Debt Solutions Group" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-75G88G16KG"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-75G88G16KG');`,
          }}
        />
        {/* <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-KFTPDSS');`,
          }}
        /> */}
      </Head>

      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}
