import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import "@/styles/scss/style.scss";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Script from "next/script";
import { GTM_ID, pageview } from "../lib/gtm";

export default function App({ Component, pageProps, isHome }) {
  const router = useRouter();
  useEffect(() => {
    router.events.on("routeChangeComplete", pageview);
    return () => {
      router.events.off("routeChangeComplete", pageview);
    };
  }, [router.events]);
  return (
    <>
      <Head>
        <title>Debt Solutions Group</title>
        <meta name="description" content="Generated by Debt Solutions Group" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* Google Tag Manager - Global base code */}
        <Script
          id="gtag-base"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer', '${GTM_ID}');
          `,
          }}
        />
      </Head>

      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}
