import Link from "next/link";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Container, Row, Col } from "react-bootstrap";
import Carousel from "react-bootstrap/Carousel";
import SliderProcess from "./components/processSlider";
import BlogSlider from "./components/blogSlider";
import { useRouter } from "next/router";
import "aos/dist/aos.css";

export default function Home() {
  const router = useRouter();

  // Bootstra carousel hover pause
  const [isHovering, setIsHovering] = useState(false);

  const handleMouseEnter = () => {
    setIsHovering(true);
  };

  const handleMouseLeave = () => {
    setIsHovering(false);
  };
  // AOS animation
  useEffect(() => {
    import("aos").then((AOS) => {
      AOS.init();
    });
  }, []);
  return (
    <>
      <Head>
        <title>DebtSolutions Group</title>
        <meta name="description" content="Generated by DebtSolutions Group" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="banner-sec">
        <div className="banner-cover">
          <Carousel
            pause={!isHovering}
            fade
            controls={false}
            indicators={false}
          >
            <Carousel.Item>
              <img
                className="slider-web"
                src="images/slider-01.jpg"
                alt="Banner"
              />
            </Carousel.Item>
            <Carousel.Item>
              <img
                className="slider-web"
                src="images/slider-02.jpg"
                alt="Banner"
              />
            </Carousel.Item>
            <Carousel.Item>
              <img
                className="slider-web"
                src="images/slider-03.jpg"
                alt="Banner"
              />
            </Carousel.Item>
          </Carousel>
          <div className="banner-body">
            <div className="container-xxl">
              <div className="banner-content">
                <h2>Take control of your finances and get debt relief.</h2>
                <h4>If you're drowning in debt, we can help you.</h4>
                <div className="banner-nav">
                  <Link className="btn btn-shine btn-book" href="">
                    BOOK A FREE ASSEssMENT
                    <span className="btn-arrow"></span>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section
        className="welcome-sec sec-top-pd-lg sec-btm-pd-lg"
        data-aos="fadeIn"
      >
        <Container fluid="xxl">
          <Row>
            <Col xs="12" lg="6">
              <div className="welcome-img-cover">
                <div
                  className="welcome-img"
                  data-aos="fade-up"
                  data-aos-delay="100"
                  data-aos-duration="1000"
                >
                  <img src="images/welcome-site-img.jpg" alt="Image" />
                </div>
                <div className="d-shape">
                  <img src="images/d-shape.svg" alt="D Shape" />
                </div>
              </div>
            </Col>
            <Col xs="12" lg="6">
              <div
                className="welcome-content"
                data-aos="fade-up"
                data-aos-delay="200"
                data-aos-duration="1000"
              >
                <div className="welcome-con-hd">
                  <h1>
                    Whatever your situation, there is a
                    <span>debt-relief option for you.</span>
                  </h1>
                </div>
                <h4>
                  Debsolutions Group is a debt solutions company based in Canada
                  that specializes in debt management and debt relief services.
                </h4>
                <p>
                  They offer a range of debt solutions such as debt
                  consolidation loans, debt settlement programs, debt management
                  plans, and bankruptcy assistance to help individuals and
                  businesses struggling with debt. Debsolutions Group aims to
                  help their clients become debt-free as quickly and efficiently
                  as possible.
                </p>
                <Link className="btn btn-shine btn-book" href="javascript:;">
                  Learn More
                </Link>
              </div>
            </Col>
          </Row>
        </Container>
      </section>

      <section
        className="process-sec sec-top-pd-lg sec-btm-pd-md"
        data-aos="fadeIn"
      >
        <Container fluid="xxl">
          <Row>
            <div className="col-12">
              <div
                className="section-hd process-hd"
                data-aos="fade-up"
                data-aos-delay="100"
                data-aos-duration="1000"
              >
                <h2>
                  Four Steps <span>to Living Debt Free</span>
                </h2>
              </div>
            </div>
          </Row>
          <Row>
            <Col xs="12">
              <SliderProcess />
            </Col>
          </Row>
        </Container>
      </section>

      <section className="support-sec sec-top-pd-md" data-aos="fadeIn">
        <Container fluid="xxl">
          <Row>
            <Col xs="12" lg="6">
              <div
                className="support-content"
                data-aos="fade-up"
                data-aos-delay="100"
                data-aos-duration="1000"
              >
                <div className="section-hd">
                  <h2>
                    We're
                    <span>here to Help you</span>
                  </h2>
                </div>
                <h4>
                  Stop interest, collection calls, and garnishments, all while
                  reducing and consolidating your debt through a consumer
                  proposal or bankruptcy.
                </h4>
                <p>
                  We know how to help you regain control of your debt and life
                  and reduce financial stress.
                </p>
                <a className="btn btn-shine btn-book" href="javascript:;">
                  BOOK A FREE ASSEssMENT
                </a>
              </div>
            </Col>
            <Col xs="12" lg="6">
              <div
                className="support-img"
                data-aos="fade-up"
                data-aos-delay="100"
                data-aos-duration="1000"
              >
                <img src="images/support-img.png" alt="Image" />
              </div>
            </Col>
          </Row>
        </Container>
      </section>

      <section className="book-sec sec-top-pd-lg" data-aos="fadeIn">
        <Container fluid="xxl">
          <Row>
            <Col xs="12" lg="6">
              <div
                className="book-form-cover"
                data-aos="fade-up"
                data-aos-delay="100"
                data-aos-duration="1000"
              >
                <div className="section-hd">
                  <h2>
                    Book a Free <br />
                    <span>Assessment Session! </span>
                  </h2>
                </div>
                <div className="book-form">
                  <div className="form-group">
                    <div className="form-floating">
                      <input className="form-control" placeholder="Name" />
                      <label>Name</label>
                    </div>
                  </div>
                  <div className="form-group">
                    <div className="form-floating">
                      <input
                        className="form-control"
                        placeholder="Phone Number"
                      />
                      <label>Phone Number</label>
                    </div>
                  </div>
                  <div className="form-group">
                    <div className="form-floating">
                      <input
                        className="form-control"
                        placeholder="Email Address"
                      />
                      <label>Email Address</label>
                    </div>
                  </div>
                  <div className="form-group">
                    <div className="form-floating">
                      <select className="form-control">
                        <option>Choose your Nearest Location</option>
                        <option>Lorem ipsum</option>
                        <option>Lorem ipsum</option>
                        <option>Lorem ipsum</option>
                      </select>
                    </div>
                  </div>
                  <div className="form-group">
                    <div className="form-floating">
                      <textarea
                        className="form-control"
                        rows="5"
                        placeholder="Message"
                      ></textarea>
                      <label>Message</label>
                    </div>
                  </div>
                  <button className="btn btn-shine btn-submit">Submit</button>
                </div>
              </div>
            </Col>
            <Col xs="12" lg="6">
              <div
                className="service-cover"
                data-aos="fade-up"
                data-aos-delay="200"
                data-aos-duration="1000"
              >
                <div className="section-hd">
                  <h2>
                    Our <br />
                    <span>Debt relief Services</span>
                  </h2>
                </div>
                <div className="service-list">
                  <div className="service-item">
                    <figure>
                      <div className="img-shape">
                        <img src="images/d-shape.svg" alt="Shape" />
                      </div>
                      <i>
                        <img src="images/service-icon-01.png" alt="Service" />
                        <img
                          className="hover"
                          src="images/service-icon-wt-01.png"
                          alt="Service"
                        />
                      </i>
                    </figure>
                    <div className="service-body">
                      <h5>
                        Consumer <br />
                        Proposal
                      </h5>
                    </div>
                  </div>
                  <div className="service-item">
                    <figure>
                      <div className="img-shape">
                        <img src="images/d-shape.svg" alt="Shape" />
                      </div>
                      <i>
                        <img src="images/service-icon-02.png" alt="Service" />
                        <img
                          className="hover"
                          src="images/service-icon-wt-02.png"
                          alt="Service"
                        />
                      </i>
                    </figure>
                    <div className="service-body">
                      <h5>Bankruptcy</h5>
                    </div>
                  </div>
                  <div className="service-item">
                    <figure>
                      <div className="img-shape">
                        <img src="images/d-shape.svg" alt="Shape" />
                      </div>
                      <i>
                        <img src="images/service-icon-03.png" alt="Service" />
                        <img
                          className="hover"
                          src="images/service-icon-wt-03.png"
                          alt="Service"
                        />
                      </i>
                    </figure>
                    <div className="service-body">
                      <h5>
                        Debt Consolidation <br />
                        Loans
                      </h5>
                    </div>
                  </div>
                  <div className="service-item">
                    <figure>
                      <div className="img-shape">
                        <img src="images/d-shape.svg" alt="Shape" />
                      </div>
                      <i>
                        <img src="images/service-icon-04.png" alt="Service" />
                        <img
                          className="hover"
                          src="images/service-icon-wt-04.png"
                          alt="Service"
                        />
                      </i>
                    </figure>
                    <div className="service-body">
                      <h5>
                        Credit <br />
                        Counselling
                      </h5>
                    </div>
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </section>

      <section className="blog-sec sec-top-pd-lg sec-btm-pd-lg">
        <div className="container-xxl">
          <div className="row">
            <div className="col-12">
              <div
                className="section-hd blog-hd"
                data-aos="fade-up"
                data-aos-delay="100"
                data-aos-duration="1000"
              >
                <h2>
                  Latest <span>Blogs</span>
                </h2>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-12">
              <BlogSlider />
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
